### ISSUE TITLE
Connecting to bluetooth but connection failed!

### ISSUE THREAD

**Issue by DaiSwap** [ekahPruthvi/cynageOS#1]
Here is the message using CLI-
                                                                                
Agent registered
[bluetooth]# agent KeyboardOnly
Agent is already registered
[bluetooth]# default-agent 
Default agent request successful
[bluetooth]# power on
Changing power on succeeded
[bluetooth]# scan on
Discovery started
[CHG] Controller 00:1A:7D:DA:71:15 Discovering: yes
[CHG] Device 30:C0:1B:95:1D:C3 RSSI: -51
[CHG] Device 30:C0:1B:95:1D:C3 TxPower: 0
[bluetooth]# remove 30:C0:1B:95:1D:C3
[DEL] Device 30:C0:1B:95:1D:C3 CMF buds
Device has been removed
[NEW] Device 30:C0:1B:95:1D:C3 CMF buds
[CHG] Device 30:C0:1B:95:1D:C3 TxPower: 0
[CHG] Device 30:C0:1B:95:1D:C3 UUIDs: 0000111e-0000-1000-8000-00805f9b34fb
[CHG] Device 30:C0:1B:95:1D:C3 UUIDs: 00001108-0000-1000-8000-00805f9b34fb
[CHG] Device 30:C0:1B:95:1D:C3 UUIDs: 0000110b-0000-1000-8000-00805f9b34fb
[CHG] Device 30:C0:1B:95:1D:C3 UUIDs: 0000110d-0000-1000-8000-00805f9b34fb
[CHG] Device 30:C0:1B:95:1D:C3 UUIDs: 0000110e-0000-1000-8000-00805f9b34fb
[bluetooth]# trust 30:C0:1B:95:1D:C3
[CHG] Device 30:C0:1B:95:1D:C3 Trusted: yes
Changing 30:C0:1B:95:1D:C3 trust succeeded
[bluetooth]# pair 30:C0:1B:95:1D:C3
Attempting to pair with 30:C0:1B:95:1D:C3
[CHG] Device 30:C0:1B:95:1D:C3 Connected: yes
[CHG] Device 30:C0:1B:95:1D:C3 UUIDs: 00001101-0000-1000-8000-00805f9b34fb
[CHG] Device 30:C0:1B:95:1D:C3 UUIDs: 00001108-0000-1000-8000-00805f9b34fb
[CHG] Device 30:C0:1B:95:1D:C3 UUIDs: 0000110b-0000-1000-8000-00805f9b34fb
[CHG] Device 30:C0:1B:95:1D:C3 UUIDs: 0000110c-0000-1000-8000-00805f9b34fb
[CHG] Device 30:C0:1B:95:1D:C3 UUIDs: 0000110e-0000-1000-8000-00805f9b34fb
[CHG] Device 30:C0:1B:95:1D:C3 UUIDs: 0000111e-0000-1000-8000-00805f9b34fb
[CHG] Device 30:C0:1B:95:1D:C3 ServicesResolved: yes
[CHG] Device 30:C0:1B:95:1D:C3 Paired: yes
Pairing successful
[CHG] Device 30:C0:1B:95:1D:C3 ServicesResolved: no
[CHG] Device 30:C0:1B:95:1D:C3 Connected: no
[bluetooth]# connect 30:C0:1B:95:1D:C3
Attempting to connect to 30:C0:1B:95:1D:C3
Failed to connect: org.bluez.Error.Failed

**Comment by ekahPruthvi** [comment]
Apparently it is because of pulseaudio and pipewire interference  
[try this to fix it](https://askubuntu.com/questions/1172000/a2dp-sink-profile-connect-failed#:~:text=sudo%20apt%2Dget%20install%20pulseaudio%2Dmodule%2Dbluetooth%0Asudo%20killall%20pulseaudio%0Apulseaudio%20%2D%2Dstart%20%20%20%20%0Asudo%20systemctl%20restart%20bluetooth)
only the highlighted one and if swayosd is interfering uninstall sway-osd and then follow the commands and finally reinstall sway-osd
