### ISSUE TITLE
Help needed!!

### ISSUE THREAD

**Issue by nichroot** [ekahPruthvi/cynageOS#2]
So I just installed the setup through the script 
![IMG_20240826_000039](https://github.com/user-attachments/assets/edfb8e57-8873-410a-ac0a-4d4771e13987)
and got to an error after rebooting from sddm
![IMG_20240826_000113](https://github.com/user-attachments/assets/943e095a-33e7-40f7-81b0-97f039ecb4c5)
![IMG_20240826_000130](https://github.com/user-attachments/assets/7216328a-0259-46b2-b019-ed6d6ee0c8a5)
And also really sorry for the shitty camera quality, I'll try to send you again if it's not legible 🙂.. please do helpp

**Comment by nichroot** [comment]
Also to add to it, I noticed some kind of error about magick or something like that when the themes were getting ready, something like "convert magick" and all, don't know if that is the problem

**Comment by ekahPruthvi** [comment]
The magick error is not a problem.
It still does the job only warning is shown

**Comment by ekahPruthvi** [comment]
I guess the lavat program is not installed I might hav missed tht in the install script, I'll fix it by tonight 
U can just install the program by yourself ```yay -Sy lavat```

**Comment by ekahPruthvi** [comment]
I guess the lavat program is not installed I might hav missed tht in the install script, I'll fix it by tonight 
U can just install the program by yourself ```
yay -Sy lavat
```
And the hyprland.conf error is because, I'm guessing you don't use nvidia gpu.
You can delete those lines from the conf if you don't have nvidia gpu

**Comment by nichroot** [comment]
> I guess the lavat program is not installed I might hav missed tht in the install script, I'll fix it by tonight U can just install the program by yourself ``` yay -Sy lavat
> 
> ```
> And the hyprland.conf error is because, I'm guessing you don't use nvidia gpu.
> You can delete those lines from the conf if you don't have nvidia gpu
> ```

Hey is that something you can fix in the install script too? btw yes I'm using an amd gpu.. again thanks for the work bro 💚

**Comment by ekahPruthvi** [comment]
> > I guess the lavat program is not installed I might hav missed tht in the install script, I'll fix it by tonight U can just install the program by yourself ``` yay -Sy lavat
> > 
> > ```
> > And the hyprland.conf error is because, I'm guessing you don't use nvidia gpu.
> > You can delete those lines from the conf if you don't have nvidia gpu
> > ```
> 
> Hey is that something you can fix in the install script too? btw yes I'm using an amd gpu.. again thanks for the work bro 💚

Yupp I've fixed itt! but instead you can just remove the nvidia lines ( specified in the error log) and install lavat if you want to.

**Comment by nichroot** [comment]
> > > I guess the lavat program is not installed I might hav missed tht in the install script, I'll fix it by tonight U can just install the program by yourself ``` yay -Sy lavat
> > > ```
> > > And the hyprland.conf error is because, I'm guessing you don't use nvidia gpu.
> > > You can delete those lines from the conf if you don't have nvidia gpu
> > > ```
> > 
> > 
> > Hey is that something you can fix in the install script too? btw yes I'm using an amd gpu.. again thanks for the work bro 💚
> 
> Yupp I've fixed itt! but instead you can just remove the nvidia lines ( specified in the error log) and install lavat if you want to.

Alright so I tried removing the lines and the error was gone but there was no bar of any sort and also rofi was kinda glitching, so I reinstalled arch minimal install again and ran the script but the config error was still there while the lavat error was gone

**Comment by ekahPruthvi** [comment]
The config i can't change cuz it is required for nvidia gpus. You'll have to manually remove those lines

**Comment by ekahPruthvi** [comment]
> > > > I guess the lavat program is not installed I might hav missed tht in the install script, I'll fix it by tonight U can just install the program by yourself ``` yay -Sy lavat
> > > > ```
> > > > And the hyprland.conf error is because, I'm guessing you don't use nvidia gpu.
> > > > You can delete those lines from the conf if you don't have nvidia gpu
> > > > ```
> > > 
> > > 
> > > Hey is that something you can fix in the install script too? btw yes I'm using an amd gpu.. again thanks for the work bro 💚
> > 
> > Yupp I've fixed itt! but instead you can just remove the nvidia lines ( specified in the error log) and install lavat if you want to.
> 
> Alright so I tried removing the lines and the error was gone but there was no bar of any sort and also rofi was kinda glitching, so I reinstalled arch minimal install again and ran the script but the config error was still there while the lavat error was gone

Also what do you mean by there is no bar? The rofi glitches will be resolved after you change the theme and the wallpapers once because they have to be initialised.
I'll try to write an automatic script for that later on when I am free.

**Comment by nichroot** [comment]
This is what it currently looks like after removing the nvidia lines, sorry if I wasn't clear enough 
![Uploading IMG_20240826_202053.jpg…]()

**Comment by nichroot** [comment]
![IMG_20240826_202053](https://github.com/user-attachments/assets/be54656c-9982-4f74-8981-aee0400c7892)

**Comment by ekahPruthvi** [comment]
> ![IMG_20240826_202053](https://github.com/user-attachments/assets/be54656c-9982-4f74-8981-aee0400c7892)
> 

Oh this is fine.
It's a custom script that I personally used as a dashboard, it's set to the resolution of my monitor u can disable that in hyprland.conf line 43 delete or comment it

**Comment by ekahPruthvi** [comment]
> This is what it currently looks like after removing the nvidia lines, sorry if I wasn't clear enough 
> ![Uploading IMG_20240826_202053.jpg…]()
> 

I cannot see the image

**Comment by nichroot** [comment]
> > ![IMG_20240826_202053](https://private-user-images.githubusercontent.com/120258414/361476474-be54656c-9982-4f74-8981-aee0400c7892.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2ODYwOTAsIm5iZiI6MTcyNDY4NTc5MCwicGF0aCI6Ii8xMjAyNTg0MTQvMzYxNDc2NDc0LWJlNTQ2NTZjLTk5ODItNGY3NC04OTgxLWFlZTA0MDBjNzg5Mi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNlQxNTIzMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ODE3ZGI3NWIzNmYxOGNiMThjMDQ2YThmMmUyODQ1MWVhZTZiNzlmYmRhZmJjNTM0ODRlZTEwMWYwNGVjZDdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5EVKhRdxqfgAmT5vDERuqA0fLKFexlBBPr_l89s0VGY)
> 
> Oh this is fine. It's a custom script that I personally used as a dashboard, it's set to the resolution of my monitor u can disable that in hyprland.conf line 43 delete or comment it

No bro I'm not taking about the dashboard.. it's cool! I don't have the side bar, I guess waybar? It's neither in the top nor any sides. Is that intentional? Like do you rock a barless setup rn?

**Comment by ekahPruthvi** [comment]
> > > ![IMG_20240826_202053](https://private-user-images.githubusercontent.com/120258414/361476474-be54656c-9982-4f74-8981-aee0400c7892.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2ODYwOTAsIm5iZiI6MTcyNDY4NTc5MCwicGF0aCI6Ii8xMjAyNTg0MTQvMzYxNDc2NDc0LWJlNTQ2NTZjLTk5ODItNGY3NC04OTgxLWFlZTA0MDBjNzg5Mi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNlQxNTIzMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ODE3ZGI3NWIzNmYxOGNiMThjMDQ2YThmMmUyODQ1MWVhZTZiNzlmYmRhZmJjNTM0ODRlZTEwMWYwNGVjZDdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5EVKhRdxqfgAmT5vDERuqA0fLKFexlBBPr_l89s0VGY)
> > 
> > Oh this is fine. It's a custom script that I personally used as a dashboard, it's set to the resolution of my monitor u can disable that in hyprland.conf line 43 delete or comment it
> 
> No bro I'm not taking about the dashboard.. it's cool! I don't have the side bar, I guess waybar? It's neither in the top nor any sides. Is that intentional? Like do you rock a barless setup rn?

Ohh did u try changing themes and wallpapers, way bar will automatically come if u cycle through wallpaper 
```
Alt + arrow keys
```
And if it doesn't yet come try 
```
Super + o
```
If none of the above work then can u type waybar in the terminal and show the output?

**Comment by nichroot** [comment]
![IMG-20240827-WA0012](https://github.com/user-attachments/assets/69fb4d5d-aab1-4c9e-8e73-465f678cec99)
__

Nope didn't work :(

**Comment by ekahPruthvi** [comment]
> ![IMG-20240827-WA0012](https://github.com/user-attachments/assets/69fb4d5d-aab1-4c9e-8e73-465f678cec99)
> __
> 
> Nope didn't work :(

Ohhh That's a one time error . It sometimes comes when booting for the first time 
To fix it Go to 
```
.config/waybar/themes/catppuccin-Mocha.css
```
And copy that and paste it to
```
.config/waybar/themes/theme.css
```
And then relaunch waybar
Also check the key binding file once to get familiar with it
 it's in
```
Settings/hypr/keybindings 
```

**Comment by nichroot** [comment]
![image](https://github.com/user-attachments/assets/d28654c2-54d4-434e-964e-2fc4913c7c3d)
this is what it looks like after doing it

**Comment by nichroot** [comment]
now i get it! the keybinding for switching walls is actally super+alt+left/right, i did something in the config and now somehow it actually worked. I guess i can close it then

**Comment by ekahPruthvi** [comment]
> now i get it! the keybinding for switching walls is actally super+alt+left/right, i did something in the config and now somehow it actually worked. I guess i can close it then

Ahh neat shall I close the issue now?

**Comment by nichroot** [comment]
> > now i get it! the keybinding for switching walls is actally super+alt+left/right, i did something in the config and now somehow it actually worked. I guess i can close it then
> 
> Ahh neat shall I close the issue now?

Sure! I thought I already did

**Comment by ekahPruthvi** [comment]
> > > now i get it! the keybinding for switching walls is actally super+alt+left/right, i did something in the config and now somehow it actually worked. I guess i can close it then
> > 
> > Ahh neat shall I close the issue now?
> 
> Sure! I thought I already did

Yeahh I saw just now!!!
